### PR TITLE
Refactor most unit tests using Expect() makes them clearer, simpler and more reliable.

### PR DESCRIPTION
**Pull request by wernight**
Using Expect() makes them clearer, simpler and more reliable.

### CODE REVIEW

**Comment by wernight** [comment]
I would suggest that the unit tests get grouped in various classes and even unit test being regrouped. I've regrouped a few using multiple `Expect(() => ..., Throws...)` and also regrouped one using `[Values()]` notation.

**Comment by adrianaisemberg** [comment]
I must admit that this Expect() thing is new to me. I'm still doing the same unit tests as learned years ago and never had the chance to move forward to a newer syntax.
I love it.

Thanks!

**Comment by wernight** [comment]
Cheers.

**Comment by adrianaisemberg** [comment]
Merged locally. Thanks!

**Pull request merged**
