### PR TITLE
Fixes https://github.com/adrianaisemberg/CLAP/issues/23

### PR DESCRIPTION
**Pull request by georgiosd**
http://stackoverflow.com/questions/57383/in-c-how-can-i-rethrow-innerexception-without-losing-stack-trace

### CODE REVIEW

**Comment by georgiosd** [comment]
https://github.com/adrianaisemberg/CLAP/issues/23

**Comment by adrianaisemberg** [comment]
That StackOverflow thread has another answer which seems cleaner and shorter. Have you tried it?

``` cs
try
{
    task.Wait();
}
catch(AggregateException ex)
{
    ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
}
```

**Comment by georgiosd** [comment]
Not really. I was in a hurry and only tried the one in the PR :)

**Comment by adrianaisemberg** [comment]
I'm merging this change. Please lets investigate the other option as-well.

Thanks!

**Pull request merged**
